# Scenario: You're in an enterprise that can't use Debian/Alpine official images, and you need to create something on CentOS/Ubuntu/etc.
# In this case, make an image that starts from latest official CentOS image, and then install the binaries of Node. 
# To do this, I go to the official repo and see how the official Node image devs' GH repo does it. 
# You can use ENV to specify the Node version -- You're not building Node but just copying the binary.
# https://hub.docker.com/_/node
# https://hub.docker.com/_/centos
# Expect this to take a few tries.
# This is useful for us to understand. It's a good idea to take an app you've been using for a while and then make it again.
# But don't do it unless you absolutely have to.


